language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script: 
  - pytest -v ./v3/asyncio
notifications:
  email:
    recipients:
      - ademin@gmail.com
    on_success: always
    on_failure: always
