dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script: 
  - python ./v3/asyncio/make.py test
notifications:
  email:
    recipients:
      - ademin@gmail.com
    on_success: always
    on_failure: always
